name: CI

on:
  push:
    branches:
      - master
      - battle_engine
      - pokemon_expansion
      - item_expansion
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Checkout mgba
        uses: actions/checkout@v2
        with:
          path: mgba
          repository: mgba-emu/mgba

      - name: Install binutils
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      - name: Agbcc
        run: make -j${nproc} -O all

      - name: Modern
        env:
          MODERN: 1
          COMPARE: 0
        run: make -j${nproc} -O all

      - name: Install mgba-rom-test
        run: |
          cmake -DCMAKE_INSTALL_PREFIX=../tools -DM_CORE_GB=OFF -DUSE_DISCORD_RPC=OFF -DUSE_EDITLINE=OFF -DUSE_EPOXY=OFF -DUSE_FFMPEG=OFF -DUSE_GDB_STUB=OFF -DUSE_LIBZIP=OFF -DUSE_LUA=OFF -DUSE_MINIZIP=OFF -DUSE_SQLITE3=OFF -DDISABLE_FRONTENDS=ON -DBUILD_ROM_TEST=ON
          make -j${nproc} -O mgba-rom-test
        working-directory: mgba

      - name: Test
        run: |
          make -j${nproc} -O pokeemerald-test.elf
          make -j${nproc} check
        env:
          ROMTEST: mgba/test/mgba-rom-test
